version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-trading-ideas
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///data/news_trading.db
      - LOG_LEVEL=info
    volumes:
      # Persist database
      - ./data:/app/data
      # Mount source code for development (hot reload)
      - ./backend:/app/backend
      - ./frontend/dist:/app/backend/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - news-trading-network

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    container_name: news-trading-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - news-trading-network
    profiles:
      - production

networks:
  news-trading-network:
    driver: bridge

volumes:
  data:
    driver: local
